#!/usr/bin/env php
<?php


if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require_once(__DIR__.'/vendor/autoload.php');
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
}



$logger=new \phlop\CliLog();
#$logger->setMinLogLevel(2);
/*
$logger->debug('DEBUG');
$logger->info('INFO');
$logger->notice('NOTICE');
$logger->warning('WARNING');
$logger->error('ERROR');
$logger->critical('CRITICAL');
$logger->alert('ALERT');
$logger->emergency('EMERGENCY');
*/



$stages=$_SERVER['argv'];
array_shift($stages);



if(!count($stages)){
    $stages[]='default';
    $logger->info('no stages set via cli, using stage "default"');
}else{
    $logger->info('running stages: '.implode(", ",$stages));
}

$buildOk=true;
$app=new \phlop\Application();
$app->setLogger($logger);
$retval=$app->init()->runStages($stages);
if($retval){
    $logger->emergency("Last action did not finish");
    $logger->emergency("BUILD FAILED");
    die((int)$retval);
}


